services:

  product-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - products-network
    depends_on:
      - products-db

  products-db:
    container_name: products-db
    image: postgres:latest
    ports:
      - 5433:5433
    logging:
      options:
        max-size: 10m
    volumes:
      - './db_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      PGPORT: ${DATABASE_PORT}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - products-network

networks:
  products-network:
    driver: bridge

# volumes:
#   db_data: